
services:
  app:
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    ports: 
      - "8080:80"
    volumes:
     - ./app:/opt/app
    environment:
     - ASPNETCORE_URLS=http://+:80
    command: ["dotnet", "/opt/app/api/bin/Debug/net5.0/api.dll"]

  sdk:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    volumes:
     - ./app:/opt/app


